// template-runtime-react-ts/page/App.tsx
import React, { useContext } from 'react';

import type TMagicApp from '@tmagic/core';
import { AppContent, useDsl } from '@tmagic/react-runtime-help';

function App() {
  const app = useContext<TMagicApp | undefined>(AppContent);

  const { pageConfig } = useDsl(app);

  const MagicUiPage = app?.resolveComponent('page');

  return <MagicUiPage config={pageConfig}></MagicUiPage>;
}

export default App;

// template-runtime-vue-ts/page/App.vue
<template>
  <component :is="pageComponent" :config="(pageConfig as MPage)"></component>
</template>

<script lang="ts" setup>
import type { MPage } from '@tmagic/core';
import { useComponent, useDsl } from '@tmagic/vue-runtime-help';

const { pageConfig } = useDsl();
const pageComponent = useComponent('page');
</script>
